/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    alias(libs.plugins.indra)
    alias(libs.plugins.indraPublishing)
}

indra {
    javaVersions {
        target(17)
        minimumToolchain(17)
        testWith(17, 21)
    }

    publishSnapshotsTo("paperSnapshots", "https://repo.papermc.io/repository/maven-snapshots")
    publishReleasesTo("paperReleases", "https://repo.papermc.io/repository/maven-releases")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
}

